/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DIDRegistry } from "./DIDRegistry";
export * as factories from "./factories";
export { DIDRegistry__factory } from "./factories/DIDRegistry__factory";
